title: Chloe J. Hill
description: 'I am a sustainability communications specialist and futures strategist.'
author: "Chloe J. Hill"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chloe-personal-dev.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
get_form_id: '' # https://getform.io/
color_scheme: 'green' #  blue/  green/  pink/  purple/  red/  yellow/
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


##########################################################################
################# seo ####################################################
##########################################################################
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :
og_image                 : '' # Open Graph/Twitter default site image
header:
  - image                 : ''

###########################################################################
########### start section            ######################################
###########################################################################

home_style:  'background-color' # background-color (default), "background-color", "particles-bg", "video-bg"

first_name: Chloe J.
last_name: Hill
email: chloe@hucklebe.com
phone: +123 654 78900
profession: "I am a sustainability communications specialist and futures strategist."
author_description: "<strong>Hello, I’m a Patrick</strong>, web-developer based on Paris. <br> I have rich experience in web site design &amp; building <br> and customization. Also I am good at <strong>html, css, <br> wordpress, php, jquery, bootstrap.</strong>"
social_link:
  - name: facebook
    text: ""
    link: "#"
    icon: "icon ion ion-social-facebook"

  - name: github
    text: ""
    link: "#"
    icon: "icon ion ion-social-github"

  - name: twitter
    text: ""
    link: "#"
    icon: "icon ion ion-social-twitter"

  - name: youtube
    text: ""
    link: "#"
    icon: "icon ion ion-social-youtube"

  - name: googleplus
    text: ""
    link: "#"
    icon: "icon ion ion-social-googleplus"


######### about section ######################

about_section:
  title: "Transitioning you to a better future"
  description: ' <p>Through leveraging a powerful combination of transformative communications, deep sustainability expertise, strategic foresight, future visioning and conscious leadership, my purpose is to help you reimagine your sustainability agenda, position your brand as a sustainability leader and equip you with the knowledge and tools that not only scale and deliver lasting impact but that also inspire behaviour change.</p>
    
####### service section ##########
service_title: 'My Toolbox unpacked
service_description: 'ut enim ad minim veniam, quis nostrud exercitation ullamco laboris'

service:
  - title: 'ui/ux design'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'web application'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'mobile application'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'brand identity'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'writing'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'photography'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'

########### works sections ###############
portfolio_title: 'recent works'
portfolio_description: 'ut enim ad minim veniam, quis nostrud exercitation ullamco laboris'
portfolios:
  - image: 'images/works/iucn.jpg'
    title: 'Realistic Business Cards MockUp'
    description: 'Here’s a new b-cards mock-up with several business cards scattered across the scene. The PSD file allows you to easily. Here’s a new b-cards mock-up with several business cards scattered across the scene.'
    link: '#'

  - image: 'images/works/n4h.jpg'
    title: 'The Mountainbiker Freebie'
    description: 'The freebie of the day is a logo design kit with an original theme that will help you create stunning mountain bike related logos in just minutes.'
    link: '#'

  - image: 'images/works/nesta.jpg'
    title: 'Notebook MockUp PSD'
    description: 'Today we’re happy to share with you the mockup of a classic notebook that will help you showcase your drawings. Today we’re happy to share with you the mockup of a classic notebook that will help.'
    link: '#'

  - image: 'images/works/page.jpg'
    title: 'Capitalist Icons'
    description: 'Today we have for you a set of 20 icons available in 2 styles: colored flat and line version, designed on a 128px grid. These polished icons come in multiple formats so you can easily include them in your projects.'
    link: '#'

  - image: 'images/works/pbl.jpg'
    title: 'Mapogo UI Kit'
    description: 'Mapogo is an expertly crafted UI kit perfect for iOS designers and developers. The free sample includes 10 screens (750×1334 px) that can be easily customized in Photoshop'
    link: '#'

  - image: 'images/works/wb.jpg'
    title: 'Chameleon UI Kit'
    description: 'The freebie of the day is Chameleon, a modern UI kit perfect to use for creating a stylish and clean mobile app. This kit includes 10 screens from various categories that can be easily edited.'
    link: '#'

  - image: 'images/works/wwf.jpg'
    title: 'Chameleon UI Kit'
    description: 'The freebie of the day is Chameleon, a modern UI kit perfect to use for creating a stylish and clean mobile app. This kit includes 10 screens from various categories that can be easily edited.'
    link: '#'

####### clients section ##########
clients_title: 'Clients'
      <div class="container content">
        <div class="row col-sm-12">
        </div>
        <div class="row">
          <!-- Begin: each line is a CLIENT -->
          <div class="col-md-3 col-sm-6"><img src="images/clients/gain.jpg" alt="GAIN" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/cbd.png" alt="CBD" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/iucn.png" alt="IUCN" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/unenvironment.png" alt="UN Environment" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/undp.jpg" alt="UNDP" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/wwf.jpg" alt="WWF" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/toak.png" alt="TOAK" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/inclusion.png" alt="Inclusion" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/LFL.png" alt="LFL" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/EC.png" alt="EC" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/world-bank-logo.jpg" alt="World Bank" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/CAD.png" alt="cad" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/pbl.png" alt="pbl" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/fairtrade.png" alt="fairtrade" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/revolve.png" alt="revolve" class="client-logo"></div>
          <div class="col-md-3 col-sm-6"><img src="images/clients/seea.png" alt="seea" class="client-logo"></div>
          <!-- End: each line is a CLIENT -->
        </div>
      </div>

      <!-- END CLIENTS SECTION -->

