title: Noisee - Personal/CV/Resume HTML Template
description: 'vCard & Resume Template'
author: "Noisee"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patrick-jekyll-demo.ducor.vercel.app" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
get_form_id: '' # https://getform.io/
color_scheme: 'green' #  blue/  green/  pink/  purple/  red/  yellow/
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


##########################################################################
################# seo ####################################################
##########################################################################
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :
og_image                 : '' # Open Graph/Twitter default site image
header:
  - image                 : ''

###########################################################################
########### start section            ######################################
###########################################################################

home_style:  'particles-bg' # background-color (default), "background-color", "particles-bg", "video-bg"

first_name: John
last_name: Brodie
email: adlard@example.com
phone: +123 654 78900
profession: "ux/ui designer & front-end developer"
author_description: "<strong>Hello, I’m a Patrick</strong>, web-developer based on Paris. <br> I have rich experience in web site design &amp; building <br> and customization. Also I am good at <strong>html, css, <br> wordpress, php, jquery, bootstrap.</strong>"
social_link:
  - name: facebook
    text: ""
    link: "#"
    icon: "icon ion ion-social-facebook"

  - name: github
    text: ""
    link: "#"
    icon: "icon ion ion-social-github"

  - name: twitter
    text: ""
    link: "#"
    icon: "icon ion ion-social-twitter"

  - name: youtube
    text: ""
    link: "#"
    icon: "icon ion ion-social-youtube"

  - name: googleplus
    text: ""
    link: "#"
    icon: "icon ion ion-social-googleplus"


######### about section ######################

about_section:
  image: 'images/man.jpg'
  title: "let me introduce myself"
  description: ' <p> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Sed ut perspiciatis unde omnis iste natus error.</p><p> Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. </p>'
  download:
    text: 'Download Resume'
    link: '#'
  hire:
    text: 'hire me'
    link: '#'
####### service section ##########
service_title: 'what i do'
service_description: 'ut enim ad minim veniam, quis nostrud exercitation ullamco laboris'

service:
  - title: 'ui/ux design'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'web application'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'mobile application'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'brand identity'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'writing'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'
  - title: 'photography'
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'

########### works sections ###############
portfolio_title: 'recent works'
portfolio_description: 'ut enim ad minim veniam, quis nostrud exercitation ullamco laboris'
portfolios:
  - image: 'images/works/work1.jpg'
    title: 'Realistic Business Cards MockUp'
    description: 'Here’s a new b-cards mock-up with several business cards scattered across the scene. The PSD file allows you to easily. Here’s a new b-cards mock-up with several business cards scattered across the scene.'
    link: '#'

  - image: 'images/works/work2.jpg'
    title: 'The Mountainbiker Freebie'
    description: 'The freebie of the day is a logo design kit with an original theme that will help you create stunning mountain bike related logos in just minutes.'
    link: '#'

  - image: 'images/works/work3.jpg'
    title: 'Notebook MockUp PSD'
    description: 'Today we’re happy to share with you the mockup of a classic notebook that will help you showcase your drawings. Today we’re happy to share with you the mockup of a classic notebook that will help.'
    link: '#'

  - image: 'images/works/work4.jpg'
    title: 'Capitalist Icons'
    description: 'Today we have for you a set of 20 icons available in 2 styles: colored flat and line version, designed on a 128px grid. These polished icons come in multiple formats so you can easily include them in your projects.'
    link: '#'

  - image: 'images/works/work5.jpg'
    title: 'Mapogo UI Kit'
    description: 'Mapogo is an expertly crafted UI kit perfect for iOS designers and developers. The free sample includes 10 screens (750×1334 px) that can be easily customized in Photoshop'
    link: '#'

  - image: 'images/works/work6.jpg'
    title: 'Chameleon UI Kit'
    description: 'The freebie of the day is Chameleon, a modern UI kit perfect to use for creating a stylish and clean mobile app. This kit includes 10 screens from various categories that can be easily edited.'
    link: '#'

####### clients section ##########
clients_title: 'Clients'
clients_description: 'ut enim ad minim veniam, quis nostrud exercitation ullamco laboris'

client:
  - name: 'ui/ux design'
    image: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis et tortor ac tincidunt. In euismod iaculis lobortis.'

